import { config } from 'dotenv';
import { spawn } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

config({ path: resolve(process.cwd(), '.env') });
config({ path: resolve(process.cwd(), '.env.local'), override: true });

const vars = [
  'NG_APP_FIREBASE_API_KEY',
  'NG_APP_FIREBASE_AUTH_DOMAIN',
  'NG_APP_FIREBASE_PROJECT_ID',
  'NG_APP_FIREBASE_APP_ID',
];

const missing = vars.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`Missing required env vars: ${missing.join(', ')}`);
  process.exit(1);
}

const envFile = `// AUTO-GENERATED by scripts/build.mjs — do not edit, do not commit values.
export const environment = {
  firebase: {
    apiKey: ${JSON.stringify(process.env.NG_APP_FIREBASE_API_KEY)},
    authDomain: ${JSON.stringify(process.env.NG_APP_FIREBASE_AUTH_DOMAIN)},
    projectId: ${JSON.stringify(process.env.NG_APP_FIREBASE_PROJECT_ID)},
    appId: ${JSON.stringify(process.env.NG_APP_FIREBASE_APP_ID)},
  },
};
`;

writeFileSync(resolve(process.cwd(), 'src/environments/environment.ts'), envFile);
console.log('Generated src/environments/environment.ts with prod values');

const child = spawn('ng build', { stdio: 'inherit', shell: true });
child.on('exit', code => process.exit(code ?? 0));
